{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.25/toolkit-core-0.2.25.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-release.aar",
          "url": "toolkit-core-android-0.2.25.aar",
          "size": 86331,
          "sha512": "e012ac1e98161bf02bf3f8de62b919eb6b0aadd57da8a7c744b828c880381b57c31fd8ff54e180539a11d1190e58100a2bd5141140fa57d17b04f16f4f5f3a63",
          "sha256": "c5c5e7fba52b4050ba64d2b61fd98348617af2ac2a7b95b40ab6b2c57003fd93",
          "sha1": "8cc11ff814f88c046740eb802154cb86a7d52814",
          "md5": "3127112f3bf40d266de039f960283721"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "toolkit-core-release.aar",
          "url": "toolkit-core-android-0.2.25.aar",
          "size": 86331,
          "sha512": "e012ac1e98161bf02bf3f8de62b919eb6b0aadd57da8a7c744b828c880381b57c31fd8ff54e180539a11d1190e58100a2bd5141140fa57d17b04f16f4f5f3a63",
          "sha256": "c5c5e7fba52b4050ba64d2b61fd98348617af2ac2a7b95b40ab6b2c57003fd93",
          "sha1": "8cc11ff814f88c046740eb802154cb86a7d52814",
          "md5": "3127112f3bf40d266de039f960283721"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "toolkit-core-android-0.2.25-sources.jar",
          "url": "toolkit-core-android-0.2.25-sources.jar",
          "size": 36687,
          "sha512": "90d7bb34df84a48f1313eb8bdf3d4e12c7c4f90fc5efe8bdce3044e70173f8ab10a0b10a64928d2a8c0036011b423e023139f3166b5f97b77ecd146e3d565863",
          "sha256": "61fe5b2d88d4b63eb498abd1589c3a2ef2d280554e643d9e24d0c85490886f87",
          "sha1": "e5308b513acc975ff779cc2d8a42f1bb57d5c8d8",
          "md5": "6fa9ae9c307739a5110be2efcd9279c3"
        }
      ]
    }
  ]
}
