{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.63/lunula-core-0.2.63.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.63",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosSimulatorArm64Main-0.2.63.klib",
          "url": "lunula-core-iossimulatorarm64-0.2.63.klib",
          "size": 177800,
          "sha512": "e7acf11e7fcb53bdb1012d07bc247c73b6f94913543175d734c0c7f72f3db64d2058cf1fb3954afbce3da2bed930fd96d59b81cf27255450d8706f0bbf96ef8a",
          "sha256": "b0ca34ffe44d2e7aa45555f1d9ef9c12f7c7456f63e0c6e27550a825feb2c7f0",
          "sha1": "0d3d8e7d0bfe182493601a1623500029ebd3eb69",
          "md5": "937ea302e712d44f5ed366d324c30506"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lunula-core-iossimulatorarm64-0.2.63-sources.jar",
          "url": "lunula-core-iossimulatorarm64-0.2.63-sources.jar",
          "size": 60183,
          "sha512": "5863c1ed2855f567a5bf249f66b3ec444e2ef8ed50ad90c818bcbdae15f5e9cb03fbd6eab8dde23a3c4f671da6cd1261fa2a44f612230eabfad6dce2b2ebe775",
          "sha256": "a8467f5f7638e6cc2e9c3c700bd397a5ad8d4b792a80bf83a8aad249a960f81c",
          "sha1": "02e1b688c16da8d448e605ff82ff763a9c055e90",
          "md5": "a550be4c6ad0392b7b303e0b0e9b5db1"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iossimulatorarm64-0.2.63-metadata.jar",
          "url": "lunula-core-iossimulatorarm64-0.2.63-metadata.jar",
          "size": 261,
          "sha512": "187d5ee3ccde9b27e29fa972efc34d80650a806a7993010bf19d1d6a1750af0854b5d21271f1a358215cc6d5f6de4f2a4384f36d58cdc25c0e076175c6d03e2e",
          "sha256": "a33b6d52e77534aab924aa42cc00d5e5f34b5319289427aee12f994ea8c26a30",
          "sha1": "5ac5056da9b0983b520a1a40a328ea4d56a8c896",
          "md5": "118f9a8b50bfd7478838e173b3199056"
        }
      ]
    }
  ]
}
