{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.9/toolkit-web-0.2.9.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.9.klib",
          "url": "toolkit-web-js-0.2.9.klib",
          "size": 643349,
          "sha512": "5430bd8a71268896f5615aa1b42205069fb0aa932070f5bd7ce7c7e8ef2894d5df472a3484d432aa5705190cfdf8520d0a93c51e11a98d9596ff2e2ca14cf3f1",
          "sha256": "f773a197210c6f28bee79368d0971afc6fd7850c4fe7a571f96409fdf1b29f51",
          "sha1": "3c53ca5eedb5e317501361d19957048b0951b96d",
          "md5": "6c36d5d45fd4c5d231ddb220c622b1b5"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.9.klib",
          "url": "toolkit-web-js-0.2.9.klib",
          "size": 643349,
          "sha512": "5430bd8a71268896f5615aa1b42205069fb0aa932070f5bd7ce7c7e8ef2894d5df472a3484d432aa5705190cfdf8520d0a93c51e11a98d9596ff2e2ca14cf3f1",
          "sha256": "f773a197210c6f28bee79368d0971afc6fd7850c4fe7a571f96409fdf1b29f51",
          "sha1": "3c53ca5eedb5e317501361d19957048b0951b96d",
          "md5": "6c36d5d45fd4c5d231ddb220c622b1b5"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.9-sources.jar",
          "url": "toolkit-web-js-0.2.9-sources.jar",
          "size": 267878,
          "sha512": "036df372a9c6af6d89d854a18a2ffb05631ce7975b1be8a893abfee898816ff25628af3f4704c525792381d9a09a8972b691854b3131d765c94291a681f61c6e",
          "sha256": "7f5ceedf9418d1648a56b544fef55f28a0db44ae89959acbc0382e8f77f18a02",
          "sha1": "e659b8cb3ec5058669f0e4823c70309663b24b5a",
          "md5": "3bf3b96b72c0d91e151ebe95564d6edf"
        }
      ]
    }
  ]
}
