{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-web/0.2.30/toolkit-web-0.2.30.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-web",
    "version": "0.2.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.30.klib",
          "url": "toolkit-web-js-0.2.30.klib",
          "size": 770708,
          "sha512": "c00195b78ef26e8d7bf79865ba10f91cd77e9285d5bcb1f21f31773d9d66c0905527e0f8a23a293759f534ba03884cfc2abf685c1dd633364fed0b5d609ac857",
          "sha256": "3033d06276d316765e1dae01eb9e419e6dc2b866072a2a6d2523ca1896fd74b1",
          "sha1": "31198953531145ad267715bbaa343e86f9624c8b",
          "md5": "ddbbc8b6429c6d7f8d70c4f1729e9102"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-web-js-0.2.30.klib",
          "url": "toolkit-web-js-0.2.30.klib",
          "size": 770708,
          "sha512": "c00195b78ef26e8d7bf79865ba10f91cd77e9285d5bcb1f21f31773d9d66c0905527e0f8a23a293759f534ba03884cfc2abf685c1dd633364fed0b5d609ac857",
          "sha256": "3033d06276d316765e1dae01eb9e419e6dc2b866072a2a6d2523ca1896fd74b1",
          "sha1": "31198953531145ad267715bbaa343e86f9624c8b",
          "md5": "ddbbc8b6429c6d7f8d70c4f1729e9102"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-web-js-0.2.30-sources.jar",
          "url": "toolkit-web-js-0.2.30-sources.jar",
          "size": 331836,
          "sha512": "50cac325e069e372b08bfb3c163343b34f52fa59f82b85f7fabba8aa8fef677c72597d7eb3424c2b42ba9d0c767b612a1ac7d6e6756b776767bec00b8e893077",
          "sha256": "6dc0d646a5c52c9578075e905bbae9bbc1221f372e534dc7bf858ed66a849d4f",
          "sha1": "da9202424330c7851dad84af59140b74f9454969",
          "md5": "a22b31686e0fe5062b438d8c18cf5a31"
        }
      ]
    }
  ]
}
