{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-store/0.2.63/lunula-store-0.2.63.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-store",
    "version": "0.2.63",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.63"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-store-iosArm64Main-0.2.63.klib",
          "url": "lunula-store-iosarm64-0.2.63.klib",
          "size": 61096,
          "sha512": "f02d39c09a5dd6edce7a2017791f96fc40fa0ddd2a59bd6db31de2fc3c8d78a2f5591d3a29b58c5d1357ad49ddd3d6e2f7587d37ef982e085bce3bfbd9e634ed",
          "sha256": "0acb0a4f2fbd303a91a522c0c0e87f6d03421920ddf77af2e37bac4c7c084c64",
          "sha1": "6b37727410f43b3d0c0725beff2f1b9859fedd3f",
          "md5": "5e1859b55062a8a58d909bc318dcce26"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lunula-store-iosarm64-0.2.63-sources.jar",
          "url": "lunula-store-iosarm64-0.2.63-sources.jar",
          "size": 17798,
          "sha512": "c2025e7df6c045a483bf7dae818d9d29d3286f3dc906e503f1a0e7cd74099a697d7a7c769c39e9e3e6e14dbf8f620eaebc99f6240691a512204bd0fd94ae6c24",
          "sha256": "b7a1906c9c836e7e3393baa6682567be7e27ac44e9a87844c9ee1c655e130ce0",
          "sha1": "5d43c82693e86b3644d10c4b233a0ce975257ece",
          "md5": "cdccc626b164d639f9a9c86d8ee3df10"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.63"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-store-iosarm64-0.2.63-metadata.jar",
          "url": "lunula-store-iosarm64-0.2.63-metadata.jar",
          "size": 3829,
          "sha512": "d700d4f42eb432f770d3d3cca732aa2a7a9a2bec3c820ebf38c3b594db7f9c349154eb64760c75c710d442cf28cccac5e0ff3b64c68c37a3488518c5ac599eb6",
          "sha256": "43e1d2d2c5e4a64ab0f13f2c9d9bad0513f8bd84b7a5fcbbc4307bd66bacde05",
          "sha1": "812b67cab9ae460a1c0c59c9efd6be719379cde8",
          "md5": "615756c827a9cff95d3df581bb1a57c0"
        }
      ]
    }
  ]
}
