{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-web/0.2.50/lunula-web-0.2.50.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-web",
    "version": "0.2.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.50.klib",
          "url": "lunula-web-js-0.2.50.klib",
          "size": 819059,
          "sha512": "52727d4a97d1c4d8c7c2eed9778d87fe16ba0d5055a633617d1c31f0c21f55eac782d0dc7ef67897bc1e8012f80b95555a135a7fb8c1fdfc2e89ac4965c3969c",
          "sha256": "d2f2b1b1ca6ef30b202e69eb7adc770ef21f4e59e3be012b1bd529b4f13310ca",
          "sha1": "def227ce991b1f7bff8a7dd50bcf974ebb0fe874",
          "md5": "26edd4ce945353e1d84084073533cb89"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.lunula",
          "module": "lunula-core",
          "version": {
            "requires": "0.2.50"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-html",
          "version": {
            "requires": "0.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-web-js-0.2.50.klib",
          "url": "lunula-web-js-0.2.50.klib",
          "size": 819059,
          "sha512": "52727d4a97d1c4d8c7c2eed9778d87fe16ba0d5055a633617d1c31f0c21f55eac782d0dc7ef67897bc1e8012f80b95555a135a7fb8c1fdfc2e89ac4965c3969c",
          "sha256": "d2f2b1b1ca6ef30b202e69eb7adc770ef21f4e59e3be012b1bd529b4f13310ca",
          "sha1": "def227ce991b1f7bff8a7dd50bcf974ebb0fe874",
          "md5": "26edd4ce945353e1d84084073533cb89"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-web-js-0.2.50-sources.jar",
          "url": "lunula-web-js-0.2.50-sources.jar",
          "size": 359217,
          "sha512": "c43e68c2c8ace233b8e096f616ee37b26c403320e800799c9749f22e948c62386f6479f809eae76e6b8f7a4639b51c408cf36c96c503264df5d612b476e8de32",
          "sha256": "4caf7c0b290fa8d5a88714c8f03310cfe1a238cb93c2b5801ee94b44e30a2bef",
          "sha1": "8ae921863fb432e80703c0e9b325cc6aa38e5d17",
          "md5": "3fea6155066ece8bd810522b3c5fe4e1"
        }
      ]
    }
  ]
}
