{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.42/lunula-core-0.2.42.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.42",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-js-0.2.42.klib",
          "url": "lunula-core-js-0.2.42.klib",
          "size": 118052,
          "sha512": "d6d0af00e8a9a3ceffc64b5d3322f65f1641a1330e86a0979e05112b6101ef063aaaa833d820030c4558dbc225797fc97471d818d628bc91656e7b67d2e43453",
          "sha256": "7be30016b90397f00fd89f0adb2121ac2025c0c9cccee3b4bb44e4a5e2abe6b5",
          "sha1": "3a97a3107b49dbcd751792b9185b1e79634375b2",
          "md5": "9e554cca584b9dad12c0f03ecc55906f"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-js-0.2.42.klib",
          "url": "lunula-core-js-0.2.42.klib",
          "size": 118052,
          "sha512": "d6d0af00e8a9a3ceffc64b5d3322f65f1641a1330e86a0979e05112b6101ef063aaaa833d820030c4558dbc225797fc97471d818d628bc91656e7b67d2e43453",
          "sha256": "7be30016b90397f00fd89f0adb2121ac2025c0c9cccee3b4bb44e4a5e2abe6b5",
          "sha1": "3a97a3107b49dbcd751792b9185b1e79634375b2",
          "md5": "9e554cca584b9dad12c0f03ecc55906f"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "lunula-core-js-0.2.42-sources.jar",
          "url": "lunula-core-js-0.2.42-sources.jar",
          "size": 41135,
          "sha512": "6e60fb4c5223ab05b9e182d510a9f87b1131e5f3d3c57449674c858cc2569f6b09502fd7a7d3e78020a86cce88fe413a63eeaa9e477df90fe68fab78689646d6",
          "sha256": "830b7500fd2cbaa47abaedbf9b3b7b8eb9dd35bda1557a3df46bf50a2095206d",
          "sha1": "75835b5733c44641e7dd8794e1e24559c7540938",
          "md5": "ba748b1ee219f766e060d033fd6e0d4f"
        }
      ]
    }
  ]
}
