{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.23/toolkit-core-0.2.23.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iosSimulatorArm64Main-0.2.23.klib",
          "url": "toolkit-core-iossimulatorarm64-0.2.23.klib",
          "size": 121560,
          "sha512": "1a2166962f7a89838afba8c2e82f79d1e4bca6172ba16c5fd4318eb7b12bb0ce9d0e701e388c1e992ace48776364a14d277eafbc84a14f497d513c7d90228ce5",
          "sha256": "35ac9aa2ecf762a920a1c3234db956c2d768f8d36a9c34b856249f89135efe39",
          "sha1": "9042edc0cedc24915c651017ba5f42b18534f7f7",
          "md5": "f8fdde30ad3e164a87ab109eea9896bb"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-core-iossimulatorarm64-0.2.23-sources.jar",
          "url": "toolkit-core-iossimulatorarm64-0.2.23-sources.jar",
          "size": 36410,
          "sha512": "50eb48b75533b55c4b25906083c8f3025e2c28c83eba4df546f4cedddd502b7effee9c9ee62641208a83ff0ab45838ced4d68115c7f2045826f8602a7cf5ee68",
          "sha256": "098c89b8dec6f4f8f652c3d770ba8db8e5be11c7e04a90339a27ec6e004e99a5",
          "sha1": "16c529208c5b7db59351af05daf1bf782842ed34",
          "md5": "5efbc4fef8909e17aff4305a3220bb52"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-iossimulatorarm64-0.2.23-metadata.jar",
          "url": "toolkit-core-iossimulatorarm64-0.2.23-metadata.jar",
          "size": 261,
          "sha512": "41ac0875f03731e60741200c3b004d02d9d4714c57edb6316cd5ce268b3f18abdb4e2e66ec76fe8d8267392dd0604565217006de60bbbb36d1d9a726df15a1cd",
          "sha256": "ecb68c0559ddf2950467ec10ef4858a65d543fb6738e4f5fe28ee53ae31c6f9d",
          "sha1": "7dea66d8b1fba894f910753b0d5b1e6b48effb37",
          "md5": "3f7aace9b586d1504e9f30eee758d265"
        }
      ]
    }
  ]
}
