{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.42/lunula-core-0.2.42.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.42",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-jvm-0.2.42.jar",
          "url": "lunula-core-jvm-0.2.42.jar",
          "size": 96540,
          "sha512": "87daedaf6ea47050b2a35f16fa68979aa6f150064f633b0d4e26870ddc5eac57043309f75f4ba334443ca1658018104fffc949c03a1f0c89ba57cdea2ba51aed",
          "sha256": "17571d514756894410354311475fad508e9c011b9f82eae6ae2c84253aa9f4aa",
          "sha1": "8dd07cc7f9ab9e78cc7814afedb203f32be77484",
          "md5": "bab9fe6ca935cecccfae0ec49bfb7096"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-jvm-0.2.42.jar",
          "url": "lunula-core-jvm-0.2.42.jar",
          "size": 96540,
          "sha512": "87daedaf6ea47050b2a35f16fa68979aa6f150064f633b0d4e26870ddc5eac57043309f75f4ba334443ca1658018104fffc949c03a1f0c89ba57cdea2ba51aed",
          "sha256": "17571d514756894410354311475fad508e9c011b9f82eae6ae2c84253aa9f4aa",
          "sha1": "8dd07cc7f9ab9e78cc7814afedb203f32be77484",
          "md5": "bab9fe6ca935cecccfae0ec49bfb7096"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "lunula-core-jvm-0.2.42-sources.jar",
          "url": "lunula-core-jvm-0.2.42-sources.jar",
          "size": 41135,
          "sha512": "6e60fb4c5223ab05b9e182d510a9f87b1131e5f3d3c57449674c858cc2569f6b09502fd7a7d3e78020a86cce88fe413a63eeaa9e477df90fe68fab78689646d6",
          "sha256": "830b7500fd2cbaa47abaedbf9b3b7b8eb9dd35bda1557a3df46bf50a2095206d",
          "sha1": "75835b5733c44641e7dd8794e1e24559c7540938",
          "md5": "ba748b1ee219f766e060d033fd6e0d4f"
        }
      ]
    }
  ]
}
