{
  "formatVersion": "1.1",
  "component": {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-store-iosarm64/0.2.25/toolkit-store-iosarm64-0.2.25.module
    "url": "../../toolkit-store/0.2.25/toolkit-store-0.2.25.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.25",
========
    "url": "../../toolkit-store/0.2.24/toolkit-store-0.2.24.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.24",
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-store-iosarm64/0.2.24/toolkit-store-iosarm64-0.2.24.module
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-store-iosarm64/0.2.25/toolkit-store-iosarm64-0.2.25.module
            "requires": "0.2.25"
========
            "requires": "0.2.24"
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-store-iosarm64/0.2.24/toolkit-store-iosarm64-0.2.24.module
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-store-iosarm64/0.2.25/toolkit-store-iosarm64-0.2.25.module
          "name": "toolkit-store-iosArm64Main-0.2.25.klib",
          "url": "toolkit-store-iosarm64-0.2.25.klib",
          "size": 44815,
          "sha512": "ef2414ec740a84012dfbfa1ee7ddec00928a86580f294276c8fbba9806a20d03ab9a92df6cc35317eb786824179c2165bc8e37c79af524a616ea73ecbe38d4da",
          "sha256": "5cea65d41f36f9c4c379428ec17e046ade306e75dacb4a428bf327ae6d0b7ab8",
          "sha1": "c982d69ac643b2cd307cb9f08d0cbc08a7f90e7c",
          "md5": "3dd63c8a63ae4dccbab9b88b37eb1801"
========
          "name": "toolkit-store-iosArm64Main-0.2.24.klib",
          "url": "toolkit-store-iosarm64-0.2.24.klib",
          "size": 44811,
          "sha512": "0934981b7b477006da96473890f814bc92968b722d8b58e6fe0db8108fcc1bacab498f6e440916c09c303ef5f8c28fb08fa9367122a977fd785b74fba3bf1670",
          "sha256": "9ed49d06956147bf40ce2b684b043dc2aa460f572f000a7f04f56983a5c11171",
          "sha1": "636bf16e8b871a83080ef6e280abd8e38707eb73",
          "md5": "e96e0ab874bd234f1e2e4be64517b427"
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-store-iosarm64/0.2.24/toolkit-store-iosarm64-0.2.24.module
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-store-iosarm64/0.2.25/toolkit-store-iosarm64-0.2.25.module
          "name": "toolkit-store-iosarm64-0.2.25-sources.jar",
          "url": "toolkit-store-iosarm64-0.2.25-sources.jar",
========
          "name": "toolkit-store-iosarm64-0.2.24-sources.jar",
          "url": "toolkit-store-iosarm64-0.2.24-sources.jar",
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-store-iosarm64/0.2.24/toolkit-store-iosarm64-0.2.24.module
          "size": 13757,
          "sha512": "787276d15fa9af841b1fa66b73895da3875289a6a037c7e408725edef7c3f80b49be1b569ec2943ca309347390c219c29b3103b47c68491eeae47ccb03499ced",
          "sha256": "cd806bfef522f3138bab592e1c385d662e3bc90dbc34423a40f17163776cee88",
          "sha1": "bbbfcef44773ae04d02753d4e48012260da71a78",
          "md5": "e37a51a7ee22ecb62ea45dcb1fb8caf9"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-store-iosarm64/0.2.25/toolkit-store-iosarm64-0.2.25.module
            "requires": "0.2.25"
========
            "requires": "0.2.24"
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-store-iosarm64/0.2.24/toolkit-store-iosarm64-0.2.24.module
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-store-iosarm64/0.2.25/toolkit-store-iosarm64-0.2.25.module
          "name": "toolkit-store-iosarm64-0.2.25-metadata.jar",
          "url": "toolkit-store-iosarm64-0.2.25-metadata.jar",
          "size": 3865,
          "sha512": "04b90be1fac4998be67ff1da2fe106314facb7b47c215cf9e19fe89ab20fda143978219de852d7a29826e1b6fdbccded8b8c580cb0724bafca815bf016128fa3",
          "sha256": "b5ad73bbacc3cee6781b3230ed6d555a077b5c3d08d6dbd70a47553d1cb935d4",
          "sha1": "81413065f19a1397160a8d670242827dcaf7041d",
          "md5": "6e4e53f5c03d9d545bcff4a3f2660ca7"
========
          "name": "toolkit-store-iosarm64-0.2.24-metadata.jar",
          "url": "toolkit-store-iosarm64-0.2.24-metadata.jar",
          "size": 3865,
          "sha512": "b9939e33067f48b0084311d96cae26a9816cc765c3c867de0bfcde03d545eb4212550253f7fb5ce5a0eb54f3cc710673fe8dab26a34acc53bc1b949b42db69fd",
          "sha256": "0bcbda83a9e5eb72bc847ffa15262c477a6eb0b9c2261ebca36f9a224ca2366c",
          "sha1": "7232a1c55279c7e990b57440c90e25858a8ab7e4",
          "md5": "207c84fe05c7a8c94defa35432368518"
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-store-iosarm64/0.2.24/toolkit-store-iosarm64-0.2.24.module
        }
      ]
    }
  ]
}
