{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.42/lunula-core-0.2.42.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.42",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-release.aar",
          "url": "lunula-core-android-0.2.42.aar",
          "size": 92679,
          "sha512": "3d08a80a9eb884cd1c99cd113cadd0d192e92f85e24ffcc180e5ae947c50cf743af9a2c24854fe8cc3c663f87d9324a11c862a02267da831128e28096faab20e",
          "sha256": "6c4ac44628417dea4f2c5fec28dbe46533390d05443fa4a4a8e3ee83134cab30",
          "sha1": "871aae265700205d1380c4bf1c41b5b24ef2dd7f",
          "md5": "371bf74554cb8d71906e13bee412f221"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "lunula-core-release.aar",
          "url": "lunula-core-android-0.2.42.aar",
          "size": 92679,
          "sha512": "3d08a80a9eb884cd1c99cd113cadd0d192e92f85e24ffcc180e5ae947c50cf743af9a2c24854fe8cc3c663f87d9324a11c862a02267da831128e28096faab20e",
          "sha256": "6c4ac44628417dea4f2c5fec28dbe46533390d05443fa4a4a8e3ee83134cab30",
          "sha1": "871aae265700205d1380c4bf1c41b5b24ef2dd7f",
          "md5": "371bf74554cb8d71906e13bee412f221"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "lunula-core-android-0.2.42-sources.jar",
          "url": "lunula-core-android-0.2.42-sources.jar",
          "size": 41135,
          "sha512": "6e60fb4c5223ab05b9e182d510a9f87b1131e5f3d3c57449674c858cc2569f6b09502fd7a7d3e78020a86cce88fe413a63eeaa9e477df90fe68fab78689646d6",
          "sha256": "830b7500fd2cbaa47abaedbf9b3b7b8eb9dd35bda1557a3df46bf50a2095206d",
          "sha1": "75835b5733c44641e7dd8794e1e24559c7540938",
          "md5": "ba748b1ee219f766e060d033fd6e0d4f"
        }
      ]
    }
  ]
}
