{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-store/0.2.31/toolkit-store-0.2.31.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iosSimulatorArm64Main-0.2.31.klib",
          "url": "toolkit-store-iossimulatorarm64-0.2.31.klib",
          "size": 61155,
          "sha512": "1556c72bcb6f4583119a9d1296792655fc1e05547506634a1d17108b6241c9c104366364e4a356f9ffe7f1ead550592f78884b87d909ffd46930242ebb3d769a",
          "sha256": "50b577af51b5a8d8f0d087c34aa0596a2462aa9ee97b8bf82d73a2980199a570",
          "sha1": "fd5548ae0b4e5524d7762de6b73b3a728083c146",
          "md5": "b6a9c8ee0cdc5fad0aecc0478a7fab2a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "toolkit-store-iossimulatorarm64-0.2.31-sources.jar",
          "url": "toolkit-store-iossimulatorarm64-0.2.31-sources.jar",
          "size": 17779,
          "sha512": "e2f6d3ef4c2984fb2d537b8c3c1102a3044da7ff7ba2f2ed72193ca56671133374fb8b803c4e2a83d696a6c5c52ceafcc36c183203070399d132388e790c6645",
          "sha256": "b4dab38a27904aa897f56c2f8b2ccc7c2513fd6508b7101fa8f42b8689234256",
          "sha1": "dd2a80c36e2049e1d96ef2483d5131de4285c613",
          "md5": "3064e8bf869402ff092488e955d7d0c8"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
            "requires": "0.2.31"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-iossimulatorarm64-0.2.31-metadata.jar",
          "url": "toolkit-store-iossimulatorarm64-0.2.31-metadata.jar",
          "size": 3865,
          "sha512": "3a0853687c8dc820fdf6543828f73802d1775dee7ffcd52bbf1d386df478666e874fb124308b7db02e9ac5155a0fe322db048725b964357485d665114c11040c",
          "sha256": "7063a1a6c4eb474824a67325655469994a41c918a6429f4c8da1d53ec99d51c7",
          "sha1": "58282cbda18447f7f92072d8f3ae879b631542ef",
          "md5": "2e55fe2ba638a86d622a6c9af17e309c"
        }
      ]
    }
  ]
}
