{
  "formatVersion": "1.1",
  "component": {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-compose-jvm/0.2.25/toolkit-compose-jvm-0.2.25.module
    "url": "../../toolkit-compose/0.2.25/toolkit-compose-0.2.25.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-compose",
    "version": "0.2.25",
========
    "url": "../../toolkit-compose/0.2.24/toolkit-compose-0.2.24.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-compose",
    "version": "0.2.24",
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-compose-jvm/0.2.24/toolkit-compose-jvm-0.2.24.module
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-compose-jvm/0.2.25/toolkit-compose-jvm-0.2.25.module
            "requires": "0.2.25"
========
            "requires": "0.2.24"
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-compose-jvm/0.2.24/toolkit-compose-jvm-0.2.24.module
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-compose-jvm/0.2.25/toolkit-compose-jvm-0.2.25.module
          "name": "toolkit-compose-jvm-0.2.25.jar",
          "url": "toolkit-compose-jvm-0.2.25.jar",
========
          "name": "toolkit-compose-jvm-0.2.24.jar",
          "url": "toolkit-compose-jvm-0.2.24.jar",
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-compose-jvm/0.2.24/toolkit-compose-jvm-0.2.24.module
          "size": 3487,
          "sha512": "19b8a19bb62e7e51a86b0ec4720032276b660bc6d7069b456f2c2f8b27538d4c6259f548331440a70ca472b06765e3ea38a0b95f8755e322ab74cad35db4c2b8",
          "sha256": "7b73aa65e8899c58500a6b33f569a28b7cd644f1bd827d528c0b10af1d30c2f0",
          "sha1": "0840963e214b074a0266eee7d95cd105ee1ffd92",
          "md5": "5eed3582f9847a65ac17124b5bad838a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-compose-jvm/0.2.25/toolkit-compose-jvm-0.2.25.module
            "requires": "0.2.25"
========
            "requires": "0.2.24"
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-compose-jvm/0.2.24/toolkit-compose-jvm-0.2.24.module
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.3"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.3"
          }
        }
      ],
      "files": [
        {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-compose-jvm/0.2.25/toolkit-compose-jvm-0.2.25.module
          "name": "toolkit-compose-jvm-0.2.25.jar",
          "url": "toolkit-compose-jvm-0.2.25.jar",
========
          "name": "toolkit-compose-jvm-0.2.24.jar",
          "url": "toolkit-compose-jvm-0.2.24.jar",
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-compose-jvm/0.2.24/toolkit-compose-jvm-0.2.24.module
          "size": 3487,
          "sha512": "19b8a19bb62e7e51a86b0ec4720032276b660bc6d7069b456f2c2f8b27538d4c6259f548331440a70ca472b06765e3ea38a0b95f8755e322ab74cad35db4c2b8",
          "sha256": "7b73aa65e8899c58500a6b33f569a28b7cd644f1bd827d528c0b10af1d30c2f0",
          "sha1": "0840963e214b074a0266eee7d95cd105ee1ffd92",
          "md5": "5eed3582f9847a65ac17124b5bad838a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-compose-jvm/0.2.25/toolkit-compose-jvm-0.2.25.module
          "name": "toolkit-compose-jvm-0.2.25-sources.jar",
          "url": "toolkit-compose-jvm-0.2.25-sources.jar",
========
          "name": "toolkit-compose-jvm-0.2.24-sources.jar",
          "url": "toolkit-compose-jvm-0.2.24-sources.jar",
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-compose-jvm/0.2.24/toolkit-compose-jvm-0.2.24.module
          "size": 1937,
          "sha512": "cf56103c015d2af0dc2607e9da994b2b3accf6cc83524babc96e9588a795a0901f62dc09ef0ae99034147972f96702c8d1d60c2f93484a128b66d7527b38bcdf",
          "sha256": "85be6d7729fefe0355968e891b874eb6dc0a7d5911b38ad1de8bae3d107a4166",
          "sha1": "1654a08151cfa3fe736a1dbb235433c4c633aad6",
          "md5": "9347455dabc525fd38f6efc130c2b160"
        }
      ]
    }
  ]
}
