{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.23/toolkit-core-0.2.23.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-js-0.2.23.klib",
          "url": "toolkit-core-js-0.2.23.klib",
          "size": 106622,
          "sha512": "16e2c017655febbff3cb0b7e097926375c7e43150ea54799613c74061500c5f3e3433d8dde40ddc9cf522c45357be8779115fbf2e3fbe8bf069f004c9af0fb36",
          "sha256": "f6e55fe576d4bb18782eb4c64b9bd5aa407299eb74551c8058206436acb9c07f",
          "sha1": "a8fb379b0758829f68d2e2e1352b29e61e383742",
          "md5": "85217258182f79dde2de09b17dbecd92"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-js-0.2.23.klib",
          "url": "toolkit-core-js-0.2.23.klib",
          "size": 106622,
          "sha512": "16e2c017655febbff3cb0b7e097926375c7e43150ea54799613c74061500c5f3e3433d8dde40ddc9cf522c45357be8779115fbf2e3fbe8bf069f004c9af0fb36",
          "sha256": "f6e55fe576d4bb18782eb4c64b9bd5aa407299eb74551c8058206436acb9c07f",
          "sha1": "a8fb379b0758829f68d2e2e1352b29e61e383742",
          "md5": "85217258182f79dde2de09b17dbecd92"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "toolkit-core-js-0.2.23-sources.jar",
          "url": "toolkit-core-js-0.2.23-sources.jar",
          "size": 36410,
          "sha512": "50eb48b75533b55c4b25906083c8f3025e2c28c83eba4df546f4cedddd502b7effee9c9ee62641208a83ff0ab45838ced4d68115c7f2045826f8602a7cf5ee68",
          "sha256": "098c89b8dec6f4f8f652c3d770ba8db8e5be11c7e04a90339a27ec6e004e99a5",
          "sha1": "16c529208c5b7db59351af05daf1bf782842ed34",
          "md5": "5efbc4fef8909e17aff4305a3220bb52"
        }
      ]
    }
  ]
}
