{
  "formatVersion": "1.1",
  "component": {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-store-android/0.2.25/toolkit-store-android-0.2.25.module
    "url": "../../toolkit-store/0.2.25/toolkit-store-0.2.25.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.25",
========
    "url": "../../toolkit-store/0.2.24/toolkit-store-0.2.24.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-store",
    "version": "0.2.24",
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-store-android/0.2.24/toolkit-store-android-0.2.24.module
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-store-android/0.2.25/toolkit-store-android-0.2.25.module
            "requires": "0.2.25"
========
            "requires": "0.2.24"
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-store-android/0.2.24/toolkit-store-android-0.2.24.module
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-store-release.aar",
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-store-android/0.2.25/toolkit-store-android-0.2.25.module
          "url": "toolkit-store-android-0.2.25.aar",
========
          "url": "toolkit-store-android-0.2.24.aar",
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-store-android/0.2.24/toolkit-store-android-0.2.24.module
          "size": 43332,
          "sha512": "ff2e3e54cf1fde0d5d4eb5164a47c811d6f27629e62755aa9c8dd6326b7a7839a230c198d7403685a58c61d4d65482129cb6fcf98f77b199e52f3a8908d57b1d",
          "sha256": "cd7ee52c0067024d2d5e95ca22081487e228960dc36ab4bf1be5662708182d0c",
          "sha1": "1b8171d3e4339b5175606c65d624d655b5507d2e",
          "md5": "3fb2f659031925e1d4619f27c8a3750d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "se.soderbjorn.darkness",
          "module": "toolkit-core",
          "version": {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-store-android/0.2.25/toolkit-store-android-0.2.25.module
            "requires": "0.2.25"
========
            "requires": "0.2.24"
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-store-android/0.2.24/toolkit-store-android-0.2.24.module
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "toolkit-store-release.aar",
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-store-android/0.2.25/toolkit-store-android-0.2.25.module
          "url": "toolkit-store-android-0.2.25.aar",
========
          "url": "toolkit-store-android-0.2.24.aar",
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-store-android/0.2.24/toolkit-store-android-0.2.24.module
          "size": 43332,
          "sha512": "ff2e3e54cf1fde0d5d4eb5164a47c811d6f27629e62755aa9c8dd6326b7a7839a230c198d7403685a58c61d4d65482129cb6fcf98f77b199e52f3a8908d57b1d",
          "sha256": "cd7ee52c0067024d2d5e95ca22081487e228960dc36ab4bf1be5662708182d0c",
          "sha1": "1b8171d3e4339b5175606c65d624d655b5507d2e",
          "md5": "3fb2f659031925e1d4619f27c8a3750d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
<<<<<<<< HEAD:libs-repo/se/soderbjorn/darkness/toolkit-store-android/0.2.25/toolkit-store-android-0.2.25.module
          "name": "toolkit-store-android-0.2.25-sources.jar",
          "url": "toolkit-store-android-0.2.25-sources.jar",
========
          "name": "toolkit-store-android-0.2.24-sources.jar",
          "url": "toolkit-store-android-0.2.24-sources.jar",
>>>>>>>> feature/more-3d-effects:libs-repo/se/soderbjorn/darkness/toolkit-store-android/0.2.24/toolkit-store-android-0.2.24.module
          "size": 16003,
          "sha512": "fcd2fdef76b8a04a8529f0cdeb10e24ec507a11dacb01de87938be2e51a82b6f7f904ca94eb6cc3281c7f2a53df29e5ad9e1dca42df2ba5e4d42544a7fa02846",
          "sha256": "bc0eb05c3a85f6f27801b4edf64900db3763306f634447442776df7e3c818667",
          "sha1": "c933ef734850af9e7891120d6e26be85cf35640f",
          "md5": "b80206b58fbb1b62cee013451a1f5fa8"
        }
      ]
    }
  ]
}
