{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lunula-core/0.2.50/lunula-core-0.2.50.module",
    "group": "se.soderbjorn.lunula",
    "module": "lunula-core",
    "version": "0.2.50",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iosSimulatorArm64Main-0.2.50.klib",
          "url": "lunula-core-iossimulatorarm64-0.2.50.klib",
          "size": 135418,
          "sha512": "36216bff3cf94b98cf921ee03e51d0992555358ee6cf9a533437cdde18a7532555c30c51bc89ab206c07c2142d307993bb7ff53483837bfa537d5464658b21ff",
          "sha256": "c94afff918bb7ec5604d7d6449808ad7169bb302a886cdb6a1638737d9b6bff0",
          "sha1": "78f0f1b4451e6280404453cf607dd3ec0ec4da15",
          "md5": "ecd58dcf98dfde5590a0d703b53d91dc"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lunula-core-iossimulatorarm64-0.2.50-sources.jar",
          "url": "lunula-core-iossimulatorarm64-0.2.50-sources.jar",
          "size": 41135,
          "sha512": "6e60fb4c5223ab05b9e182d510a9f87b1131e5f3d3c57449674c858cc2569f6b09502fd7a7d3e78020a86cce88fe413a63eeaa9e477df90fe68fab78689646d6",
          "sha256": "830b7500fd2cbaa47abaedbf9b3b7b8eb9dd35bda1557a3df46bf50a2095206d",
          "sha1": "75835b5733c44641e7dd8794e1e24559c7540938",
          "md5": "ba748b1ee219f766e060d033fd6e0d4f"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "lunula-core-iossimulatorarm64-0.2.50-metadata.jar",
          "url": "lunula-core-iossimulatorarm64-0.2.50-metadata.jar",
          "size": 261,
          "sha512": "cf4f82c9e321f7c914f89bda5e591453a597b39cd47464613365cef23ee2f8701393eb8a1dfa78347736031b907a43cdd80f8de8a46a70eb8e310b30e5ae25d8",
          "sha256": "d1722b3f35cb434a4659b7b637fd3b41ad44dc47abb1794b4d6d2f1a5d558fb9",
          "sha1": "74696450acf8e25ea0d336a1ebda8ddbd13d3a6f",
          "md5": "2ef574aacaee588d3e9e96725e5c60eb"
        }
      ]
    }
  ]
}
