{
  "formatVersion": "1.1",
  "component": {
    "url": "../../toolkit-core/0.2.23/toolkit-core-0.2.23.module",
    "group": "se.soderbjorn.darkness",
    "module": "toolkit-core",
    "version": "0.2.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        }
      ],
      "files": [
        {
          "name": "toolkit-core-release.aar",
          "url": "toolkit-core-android-0.2.23.aar",
          "size": 85871,
          "sha512": "5bdd6c94f04d9ffabe58dc49408b9b96e8fea6d4adf3f641bd5f0c9d59e5b0009d76aa521e16fdabde3a5e6f9c40c4002a1f6d2eac7937a985c2f474dd147db3",
          "sha256": "31d3fa29ae831e8c3f2fb310fbe76d6a900a0ee9b6d265644574c6d2148c2c03",
          "sha1": "34437464327fd716b3cc47ded4582970786d7dee",
          "md5": "44158df5f77a8cc47fbacfd09105f826"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "toolkit-core-release.aar",
          "url": "toolkit-core-android-0.2.23.aar",
          "size": 85871,
          "sha512": "5bdd6c94f04d9ffabe58dc49408b9b96e8fea6d4adf3f641bd5f0c9d59e5b0009d76aa521e16fdabde3a5e6f9c40c4002a1f6d2eac7937a985c2f474dd147db3",
          "sha256": "31d3fa29ae831e8c3f2fb310fbe76d6a900a0ee9b6d265644574c6d2148c2c03",
          "sha1": "34437464327fd716b3cc47ded4582970786d7dee",
          "md5": "44158df5f77a8cc47fbacfd09105f826"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "toolkit-core-android-0.2.23-sources.jar",
          "url": "toolkit-core-android-0.2.23-sources.jar",
          "size": 36410,
          "sha512": "50eb48b75533b55c4b25906083c8f3025e2c28c83eba4df546f4cedddd502b7effee9c9ee62641208a83ff0ab45838ced4d68115c7f2045826f8602a7cf5ee68",
          "sha256": "098c89b8dec6f4f8f652c3d770ba8db8e5be11c7e04a90339a27ec6e004e99a5",
          "sha1": "16c529208c5b7db59351af05daf1bf782842ed34",
          "md5": "5efbc4fef8909e17aff4305a3220bb52"
        }
      ]
    }
  ]
}
